default: &default
  username: aeflanta
  password: aefaefaef
  # database name
  database: "example-db"
  # influxdb api endpoint
  host: "localhost"
  port: 8086

development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
